---
repos:
    # - repo: local
    #   hooks:
    #       - id: swag-fmt
    #         name: swag-fmt
    #         entry: swag fmt
    #         language: golang
    #         pass_filenames: false
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-yaml
      # - id: check-toml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt
    - repo: https://github.com/mrtazz/checkmake.git
      rev: c047d51fe0a08be186dc0c734151793924ebb249
      hooks:
          - id: checkmake
  # - repo: https://github.com/pappasam/toml-sort.git
  #   rev: v0.22.2
  #   hooks:
  #       - id: toml-sort
  #         args: [--in-place, --all, --ignore-case]
  # - repo: https://github.com/segmentio/golines
  #   rev: v0.11.0
  #   hooks:
  #       - id: golines
  #         args: [-m, '80']
    - repo: https://github.com/dnephin/pre-commit-golang
      rev: v0.5.1
      hooks:
          - id: go-fmt
          - id: go-vet
          - id: go-imports
          # - id: go-cyclo
          #   args: [-over=15]
          - id: golangci-lint
          # - id: go-critic
          - id: go-unit-tests
          - id: go-build
          - id: go-mod-tidy
